### ISSUE TITLE
Questions about test code

### ISSUE THREAD

**Issue by cciyf** [mogproject/modular-decomposition#9]
I found that the test results seem to have inconsistent neighborhood information and inconsistent direction of edges for certain modules.
For example, in the first test sample,
{0, 2}, {0, 3}, {0, 6}, {0, 7}, {1, 6}, {2, 3}, {2, 4}, {2, 5},
{2, 7}, {3, 4}, {3, 5}, {4, 5}, {4, 6}, {4, 7}, {5, 6}, {5, 7},
The neighborhoods of 3 and 7 are not consistent, with 3->5 and 5->7, but they are considered as one module.
![graph (1)](https://github.com/mogproject/modular-decomposition/assets/26536234/b53a68e6-dcc3-45a6-ad72-65149f7c3980)

**Comment by mogproject** [comment]
We assume that all graphs are undirected. Unfortunately, we have not implemented the directed version of modular decomposition yet.

Thanks for asking!
